Add README.md to some packages
phenyl/phenyl pull request #685
Opened 2021-06-10 04:01 UTC by imoans

- Added README to all packages
- Added an overview and usage of frequently used packages

2021-06-11 01:52 UTC, imoans commented on modules/redux/README.md
> +const store = createStore(phenylReducer, enhancer);
```suggestion
const store = createStore(reducer, enhancer);
```

2021-06-19 07:01 UTC, sasurau4 requested changes
With nits

2021-06-19 07:01 UTC, sasurau4 commented on modules/central-state/README.md
> +import { MongoClient } from 'mongodb'
This code seems mongo-db example. We can't use central-state itself without db client.
Empty example would be better, I think.

2021-06-24 06:43 UTC, sasurau4 approved these changes
👍

2021-06-24 06:44 UTC, merged